let CONSTANTS = {};
CONSTANTS.CUSTOM_SOURCE_FOLDER = "ShareExtension";
CONSTANTS.CUSTOM_TARGET_NAME = "ShareExt";
CONSTANTS.CUSTOM_TARGET_SUBFOLDER = "ShareExtension";
CONSTANTS.CUSTOM_INFOPLIST_FILE = "ScreenshareInfo"
CONSTANTS.PLUGIN_ID = "cordova-plugin-sharescreen";
CONSTANTS.APP_GROUP_PREFIX = "group";
CONSTANTS.BUNDLE_SUFFIX = '.shareextension';


module.exports = CONSTANTS;